# config.yaml

# ================================
# 系统提示
# ================================
system_prompts:
  default: |
    
  error_handling: |
    
# ================================
# 领域推理设置
# ================================
domain_inference_settings:
  stem:
    prior: 0.88
    typical_samples: "What is $\\left(\\frac{7}{8}\\right)^3 \\cdot \\left(\\frac{7}{8}\\right)^{-3}$?\nIn how many ways can 4 books be selected from a shelf of 6 books if the order in which the books are selected does not matter?\nFind the distance between the points $(2,1,-4)$ and $(5,8,-3).$\nThe faces of an octahedral die are labeled with digits $1$ through $8$. What is the probability, expressed as a common fraction, of rolling a sum of $15$ with a pair of such octahedral dice?"
    difficulty_range: [1, 5]
    symbol_patterns:
      - "code"
      - "program"
      - "coding"
      - "script"
      - "paper"
      - "math"
      - "formula"
      - "tech"
      - "science"
      - "algorithm"
      - "debug"
      - "function"
      - "variable"
      - "loop"
      - "class"
      - "object"
      - "method"
      - "compile"
      - "exception"
      - "framework"
      - "API"
      - "syntax"
      - "IDE"
      - "version control"
      - "deploy"
      - "equation"
      - "proof"
      - "integral"
      - "derivative"
      - "matrix"
      - "statistics"
      - "probability"
      - "calculus"
      - "experiment"
      - "hypothesis"
      - "research"
      - "data"
      - "machine learning"
      - "neural network"
      - "AI"
      - "modeling"
      - "system design"
      - "physical laws"
      - "theory"
      - "chemistry"
      - "physics"
      - "biology"
      - "Internet"
      - "calculate"
      - "solve"
      - "find"
      - "what is"
      - "how many"
      - "prove"
      - "evaluate"
      - "determine"
      - "compute"
      - "$"
      - "\\frac"
      - "\\sqrt"
      - "\\sum"
      - "\\prod"
      - "\\int"
      - "\\lim"
      - "\\pi"
      - "\\alpha"
      - "\\beta"
      - "\\theta"
      - "\\infty"
      - "="
      - ">"
      - "<"
      - "\\leq"
      - "\\geq"
      - "\\neq"
      - "\\approx"
      - "\\times"
      - "\\div"
      - "\\pm"
      - "\\mp"
      - "\\cdot"
      - "\\log"
      - "\\ln"
      - "\\sin"
      - "\\cos"
      - "\\tan"
      - "matrix"
      - "vector"
      - "equation"
      - "function"
      - "polynomial"
      - "probability"
      - "statistics"
      - "geometry"
      - "algebra"
      - "calculus"
      - "arithmetic"
      - "sequence"
      - "series"
      - "asymptote"
      - "graph"
      - "vertical"
      - "derivative"
      - "integral"
      - "limit"
      - "differential"
      - "gradient"
      - "tensor"
      - "set"
      - "group"
      - "ring"
      - "field"
      - "modulus"
      - "determinant"
      - "eigenvalue"
      - "eigenvector"
      - "transpose"
      - "inverse"
      - "norm"
      - "dot product"
      - "cross product"
      - "inner product"
      - "outer product"
      - "homomorphism"
      - "isomorphism"
      - "bijection"
      - "permutation"
      - "combinatorics"
      - "permutation"
      - "combination"
      - "expectation"
      - "variance"
      - "covariance"
      - "correlation"
      - "entropy"
      - "bayes"
      - "stochastic"
      - "random variable"
      - "markov"
      - "conditional"
      - "independent"
      - "dependent"
      - "distribution"
      - "gaussian"
      - "poisson"
      - "binomial"
      - "uniform"
      - "normal"
      - "chi-square"
      - "f-distribution"
      - "t-distribution"
      - "hypothesis"
      - "confidence interval"
      - "sample"
      - "population"
      - "estimation"
      - "regression"
      - "logarithm"
      - "exponential"
      - "quadratic"
      - "cubic"
      - "root"
      - "modulo"
      - "factorial"
      - "prime"
      - "composite"
      - "gcd"
      - "lcm"
      - "divisibility"
      - "congruence"
      - "boolean"
      - "truth table"
      - "logic"
      - "proposition"
      - "theorem"
      - "axiom"
      - "lemma"
      - "corollary"
      - "proof"
      - "contradiction"
      - "induction"
      - "bijection"
      - "bijection"
      - "bijection"
      - "bijection"
      - "bijection"
      - "\\delta"
      - "\\epsilon"
      - "\\sigma"
      - "\\mu"
      - "\\lambda"
      - "\\rho"
      - "\\omega"
      - "\\phi"
      - "\\psi"
      - "\\Gamma"
      - "\\Delta"
      - "\\Theta"
      - "\\Lambda"
      - "\\Xi"
      - "\\Pi"
      - "\\Sigma"
      - "\\Upsilon"
      - "\\Phi"
      - "\\Psi"
      - "\\Omega"
    weights:
      overlap: 0.35
      path_distance: 0.35
      historical_similarity: 0.3


  # 可以在此处添加更多领域配置...

# ================================
# 知识图谱
# ================================
knowledge_graph:
  stem:
    concepts:
      # Mathematics
      - "algebra"
      - "geometry"
      - "calculus"
      - "statistics"
      - "probability"
      - "number theory"
      - "linear algebra"
      - "discrete mathematics"
      - "trigonometry"
      - "mathematical modeling"

      # Physics
      - "classical mechanics"
      - "thermodynamics"
      - "electromagnetism"
      - "quantum physics"
      - "optics"
      - "astronomy"
      - "nuclear physics"
      - "fluid dynamics"
      - "relativity theory"
      - "particle physics"

      # Engineering
      - "mechanical engineering"
      - "electrical engineering"
      - "civil engineering"
      - "software engineering"
      - "chemical engineering"
      - "aerospace engineering"
      - "robotics"
      - "control systems"
      - "materials science"
      - "structural analysis"

      # Technology
      - "computer programming"
      - "artificial intelligence"
      - "machine learning"
      - "data science"
      - "cybersecurity"
      - "network technology"
      - "cloud computing"
      - "database systems"
      - "web development"
      - "mobile development"

      # Applied Sciences
      - "biotechnology"
      - "nanotechnology"
      - "environmental science"
      - "renewable energy"
      - "sustainability"
      - "industrial processes"
      - "quality control"
      - "automation"
      - "3D printing"
      - "sensors and instrumentation"
    conflicts: []



# ================================
# 专家定义
# ================================
# 专家角色定义
experts:
  stem:
    - name: "Math Analysis Expert"
      domain_expertise: ["stem"]
      capabilities: {"problem_analysis": 0.95, "concept_identification": 0.9, "strategy_planning": 0.85}
      knowledge_dependencies: []
      role_prompt: "You are a math problem analysis expert." 
      task_template: |
        Analyze the following math problem:
        {{user_prompt}}
        Your tasks:
        1. Break down the key components of the problem.
        2. Recommend appropriate solving methods or strategies.
        3. Identify potential pitfalls or common misconceptions that may arise during the solving process.
        Ensure your analysis is clear, concise, and actionable. Your response should be clear and under 150 words.
      max_tokens: 300
      model: "Qwen/Qwen2.5-72B-Instruct-Turbo"
      prior_alpha: 3
      prior_beta: 2

    - name: "Math Solution Expert"
      domain_expertise: ["stem"]
      capabilities: {"problem_analysis": 0.95, "concept_identification": 0.9, "strategy_planning": 0.85}
      knowledge_dependencies: ["Math Analysis Expert"]
      role_prompt: |
        You are a math expert. Given a mathematics problem, determine the answer. Simplify your answer as much as possible. Your response should be clear with less than 600 words.
        Problem: What is $\left(\frac{7}{8}\right)^3 \cdot \left(\frac{7}{8}\right)^{-3}$?
        Answer: $\boxed{1}$
        ###
        Problem: In how many ways can 4 books be selected from a shelf of 6 books if the order in which the books are selected does not matter?
        Answer: $\boxed{15}$
        ###
        Problem: Find the distance between the points $(2,1,-4)$ and $(5,8,-3).$
        Answer: $\boxed{\sqrt{59}}$
        ###
        Problem: The faces of an octahedral die are labeled with digits $1$ through $8$. What is the probability, expressed as a common fraction, of rolling a sum of $15$ with a pair of such octahedral dice?
        Answer: $\boxed{\frac{1}{32}}$
        ###
        Problem: The first three terms of an arithmetic sequence are 1, 10 and 19, respectively. What is the value of the 21st term?
        Answer: $\boxed{181}$
        ###
        Problem: Calculate $6 \cdot 8\frac{1}{3}$
        Answer: $\boxed{50}$
        ###
        Problem: When the binary number $100101110010_2$ is divided by 4, what is the remainder (give your answer in base 10)?
        Answer: $\boxed{2}$
        ###
        Problem: How many zeros are at the end of the product 25 $\times$ 240?
        Answer: $\boxed{3}$
      task_template: |
        Problem: {{user_prompt}}
      max_tokens: 800
      model: "Qwen/Qwen2.5-72B-Instruct-Turbo"
      prior_alpha: 3
      prior_beta: 2

  # 可以在此处添加更多领域的专家定义...

# ================================
# 整合器定义
# ================================
integrator:
  default:
    name: "integrator" 
    capabilities:
      content_integration: 0.95
      quality_control: 0.90
      consistency_check: 0.85
    role_prompt: |
      You are a mathematics expert.
      Your final response must deliver a direct answer to the user, free of any references to the integration process or expert contributions.

    task_template: |
      Your task is to:  
      1. **Review and validate** the following problem and proposed solution:  
        - **Problem**: {{user_prompt}}  
        - **Proposed Solution**: {{expert_proposals}}  
      2. **Confirm the accuracy** of the solution:  
        - If correct:  
          - Ensure the final answer is in $\boxed{}$ format.  
          - If not already, rewrite the final answer with $\boxed{}$.  
          - Simplify and clarify the solution within 300 words.  
        - If incorrect:  
          - Redo the problem.  
          - Provide a correct and simplified solution, ensuring the final answer is in $\boxed{}$.  
      3. Examples of formatting:  
        - Input: "(-\infty, 0) \cup (0, +\infty)"  
          Output: "$\boxed{(-\infty, 0) \cup (0, \infty)}$"  
        - Input: "\\boxed{x = \\frac{-2}{3}}"  
          Output: "$x = \\boxed{-\\dfrac{2}{3}}$"  
        - Input: "$b = \\frac{-5}{4}$"  
          Output: "$b = \\boxed{-\\frac{5}{4}}$"  
        - Input: "The solution is $\\sqrt{2}$"
          Output: "$\\boxed{\\sqrt{2}}$"
        - Input: "$\\boxed{neither}$"
          Output: "$\\boxed{\\text{neither}}$"
        - Input: "$3.5(72)+247=\\499 \\text{dollars}$"
          Output: "$3.5(72)+247=\\boxed{499}$ dollars"
      **Key Requirements:**  
      - Provide clear, simplified solutions.  
      - Ensure proper usage of $\LaTeX$ formatting in all mathematical expressions.  
      - Keep responses concise and under 300 words.

    max_tokens: 1000
    model: "Qwen/Qwen2.5-72B-Instruct-Turbo"
    temperature: 0.7


# ================================
# 模型管理
# ================================
models:
  default: "Qwen/Qwen2.5-72B-Instruct-Turbo"  # 全局默认模型
  # 可以在此处定义其他模型版本，如有需要
  # e.g.,
  # qa_model: "Qwen/Qwen2.5-72B-Instruct-Turbo-QA"
  # academic_model: "Qwen/Qwen2.5-72B-Instruct-Turbo-Academic"

# ================================
# LLM API 配置
# ================================
llm_api:
  provider: "together"  # LLM 提供商名称，如 "together"、"openai"、"huggingface" 等
  api_key: "${TOGETHER_API_KEY}"  # 使用环境变量管理API密钥，确保安全性

# ================================
# 日志设置
# ================================
logging:
  level: "INFO"  # 日志级别，可选值：DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # 日志格式
  handlers:
    - type: "file"
      filename: "moa_system.log"  # 日志文件路径
    - type: "stream"
      stream: "stdout"  # 控制台输出

# ================================
# 其他配置（如有需要）
# ================================
# 可以在此处添加其他全局配置项，例如：
# database:
#   host: "localhost"
#   port: 5432
#   user: "${DB_USER}"
#   password: "${DB_PASSWORD}"
